./rtl/MCU.v
./rtl/Timer.v
./rtl/IntControl.v 
./rtl/IntArbiter.v
./rtl/CPU.v
./rtl/InsDecoder.v
./rtl/ALEGen.v
./rtl/ClkDiv.v
./rtl/Process.v 
./rtl/ALU.v 
./rtl/Uart.v
./rtl/UartIf.v
./rtl/UartFiFo.v
./rtl/bin2gray.v
./rtl/gray2bin.v
./rtl/fifo_ram.v