 ./src/rtl/MCU.v
 ./src/rtl/Timer.v
 ./src/rtl/IntControl.v
 ./src/rtl/IntArbiter.v
 ./src/rtl/CPU.v
 ./src/rtl/InsDecoder.v
 ./src/rtl/ALEGen.v
 ./src/rtl/ClkDiv.v
 ./src/rtl/Process.v 
 ./src/rtl/ALU.v 
 ./src/rtl/Uart.v
 ./src/rtl/UartIf.v
 ./src/rtl/UartFiFo.v
 ./src/rtl/bin2gray.v
 ./src/rtl/gray2bin.v
 ./src/rtl/fifo_ram.v